apiVersion: v1
kind: Pod
metadata:
  name: helper
spec:
  containers:
    - name: helper
      image: gcr.io/google_containers/busybox:1.27.2
      command: ["/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  restartPolicy: Never 