apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    color: red
spec:
  containers:
    - image: aldredb/node_color:1
      name: red
      env:
        - name: "COLOR"
          value: "red"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: green
  labels:
    color: green
spec:
  containers:
    - image: aldredb/node_color:1
      name: green
      env:
        - name: "COLOR"
          value: "green"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    color: blue
spec:
  containers:
    - image: aldredb/node_color:1
      name: blue
      env:
        - name: "COLOR"
          value: "blue"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    color: yellow
spec:
  containers:
    - image: aldredb/node_color:1
      name: yellow
      env:
        - name: "COLOR"
          value: "yellow"
      ports:
        - containerPort: 8080