apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: mongo
    app: todoapp
spec:
  containers:
    - image: mongo:4.0.9-xenial
      name: mongo
      ports:
      - name: mongo
        containerPort: 27017