apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    env: web
spec:
  containers:
    - name: web
      image: nginx:1.7.9
      ports:
        - containerPort: 80
          name: http-server
          protocol: TCP
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim: 
        claimName: my-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    env: web
spec:
  selector:
    env: web
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30100
      protocol: TCP